//! Challenge–Response protocol model.
//!
//! RFC 2026-08-04-node-identity-trust §3.7 / ADR-0038 §5 / ADR-0039 §5.
//!
//! The challenge is a fixed-structure message with NO timestamps; replay
//! protection comes from the one-shot state machine (`ChallengeState`), not
//! from session expiry. `canonical_bytes()` is the single source of truth for
//! the signed representation.
//!
//! SEC-001 (Challenge–Response hardening): the in-memory store adds a
//! server-side lifetime (`CHALLENGE_TTL`), a bound on outstanding challenges
//! (`MAX_OUTSTANDING_CHALLENGES`), and opportunistic expiry pruning. The
//! lifetime timestamp is stored OUTSIDE `ChallengeMessage` so the canonical
//! signed representation remains timestamp-free.

use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::domain::identity::canonical;

/// Protocol version of the challenge message.
pub const CHALLENGE_PROTOCOL_VERSION: u16 = 1;

/// Lifetime of a Pending challenge (SEC-001-B).
///
/// Interactive authentication must not leave challenges usable indefinitely.
/// 120 seconds is a short, explicit window appropriate for a single-node
/// desktop application.
pub const CHALLENGE_TTL: Duration = Duration::from_secs(120);

/// Maximum concurrently outstanding challenges (SEC-001-C).
///
/// Bounds the in-memory challenge map so repeated `begin()` calls cannot grow
/// it without limit. Conservative for a single-node desktop application: the
/// frontend holds at most one challenge per login attempt.
pub const MAX_OUTSTANDING_CHALLENGES: usize = 16;

/// Challenge scheme version — bumped only when the message semantics change.
pub const CHALLENGE_VERSION: u16 = 1;

/// A server-issued, one-shot challenge.
///
/// Fields: `protocol_version`, `session_id` (fresh, no timestamps),
/// `node_identity_id` (target node), `nonce` (32 random bytes), `challenge_version`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChallengeMessage {
    pub protocol_version: u16,
    pub session_id: uuid::Uuid,
    pub node_identity_id: uuid::Uuid,
    pub nonce: [u8; 32],
    pub challenge_version: u16,
}

impl ChallengeMessage {
    /// Build a fresh challenge bound to the target node identity.
    pub fn new(session_id: uuid::Uuid, node_identity_id: uuid::Uuid, nonce: [u8; 32]) -> Self {
        Self {
            protocol_version: CHALLENGE_PROTOCOL_VERSION,
            session_id,
            node_identity_id,
            nonce,
            challenge_version: CHALLENGE_VERSION,
        }
    }

    /// Canonical signed representation (ADR-0039 §5) — the single source of
    /// truth for signing/verification. Deterministic, no wall clock, no
    /// randomness at verification.
    ///
    /// Layout (v1): [CANONICAL_ENCODING_VERSION u16 BE][protocol_version u16 BE]
    /// [session_id 16][node_identity_id 16][nonce 32][challenge_version u16 BE] = 70 bytes.
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(70);
        canonical::write_u16(&mut out, canonical::CANONICAL_ENCODING_VERSION);
        canonical::write_u16(&mut out, self.protocol_version);
        canonical::write_uuid(&mut out, &self.session_id);
        canonical::write_uuid(&mut out, &self.node_identity_id);
        out.extend_from_slice(&self.nonce);
        canonical::write_u16(&mut out, self.challenge_version);
        out
    }
}

/// Explicit per-challenge lifecycle state (B3 design).
///
/// A single map of `(ChallengeMessage, ChallengeState)` prevents impossible
/// states (a challenge is never both pending and consumed) and allows future
/// states (e.g. `Invalidated`) without redesign.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChallengeState {
    /// Challenge issued, completion not yet attempted.
    Pending,
    /// First completion attempt received — fail-closed replay protection.
    /// The challenge can never be used again, success or failure.
    Consumed,
}

/// In-memory one-shot challenge store with server-side TTL and a bound on
/// outstanding challenges (SEC-001-B / SEC-001-C).
///
/// The wall clock is injected as Unix epoch seconds into the `*_at` methods so
/// expiry behavior is deterministic in tests; the `begin`/`consume` wrappers
/// use the real clock. No background thread prunes entries — cleanup is
/// opportunistic (on `begin`) and on consume of expired/consumed challenges.
#[derive(Debug, Default)]
pub struct IdentityChallengeState {
    challenges: std::collections::HashMap<uuid::Uuid, StoredChallenge>,
}

/// A tracked challenge plus the server-side metadata required to enforce
/// lifetime and one-shot semantics. `issued_at_epoch_secs` is generated by the
/// backend and never comes from the frontend (SEC-001-B).
#[derive(Debug, Clone)]
struct StoredChallenge {
    challenge: ChallengeMessage,
    state: ChallengeState,
    issued_at_epoch_secs: i64,
}

impl IdentityChallengeState {
    /// Real wall clock as Unix epoch seconds.
    fn now_epoch_secs() -> i64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs() as i64
    }

    /// True when a challenge issued at `issued_at_epoch_secs` has exceeded
    /// `CHALLENGE_TTL` by `now_epoch_secs`.
    fn is_expired(issued_at_epoch_secs: i64, now_epoch_secs: i64) -> bool {
        let elapsed = now_epoch_secs.saturating_sub(issued_at_epoch_secs);
        elapsed >= CHALLENGE_TTL.as_secs() as i64
    }

    /// Register a fresh challenge as `Pending` (real clock).
    ///
    /// Expired challenges are pruned first. Returns `false` when the store is
    /// already at `MAX_OUTSTANDING_CHALLENGES` (SEC-001-C).
    pub fn begin(&mut self, challenge: ChallengeMessage) -> bool {
        self.try_begin(challenge, Self::now_epoch_secs())
    }

    /// Deterministic variant of `begin` for tests: expiry pruning and the
    /// outstanding-challenge cap are evaluated against the injected clock.
    pub fn try_begin(&mut self, challenge: ChallengeMessage, now_epoch_secs: i64) -> bool {
        self.prune_expired_at(now_epoch_secs);
        if self.challenges.len() >= MAX_OUTSTANDING_CHALLENGES {
            return false;
        }
        self.challenges.insert(
            challenge.session_id,
            StoredChallenge {
                challenge,
                state: ChallengeState::Pending,
                issued_at_epoch_secs: now_epoch_secs,
            },
        );
        true
    }

    /// Atomically consume a `Pending` challenge for the first completion attempt
    /// (real clock).
    ///
    /// Fail-closed (ADR-0039 / B3): the challenge is flipped to `Consumed` on
    /// the FIRST attempt regardless of outcome, so a replayed or re-submitted
    /// message is always rejected — even after a failed passphrase attempt.
    /// An expired challenge is rejected AND removed (SEC-001-B).
    pub fn consume(&mut self, session_id: &uuid::Uuid) -> Option<ChallengeMessage> {
        self.consume_at(session_id, Self::now_epoch_secs())
    }

    /// Deterministic variant of `consume` for tests.
    pub fn consume_at(
        &mut self,
        session_id: &uuid::Uuid,
        now_epoch_secs: i64,
    ) -> Option<ChallengeMessage> {
        if let Some(entry) = self.challenges.get_mut(session_id) {
            if Self::is_expired(entry.issued_at_epoch_secs, now_epoch_secs) {
                self.challenges.remove(session_id);
                return None;
            }
            if entry.state == ChallengeState::Pending {
                entry.state = ChallengeState::Consumed;
                return Some(entry.challenge.clone());
            }
        }
        None
    }

    /// Observe the current lifecycle state of a challenge (tests / audit).
    pub fn state(&self, session_id: &uuid::Uuid) -> Option<ChallengeState> {
        self.challenges.get(session_id).map(|e| e.state)
    }

    /// Number of tracked challenges (memory bound / diagnostics).
    pub fn len(&self) -> usize {
        self.challenges.len()
    }

    /// True when no challenges are tracked.
    pub fn is_empty(&self) -> bool {
        self.challenges.is_empty()
    }

    /// Remove every expired challenge (real clock). Returns how many were
    /// removed. Cleanup is opportunistic; no background thread is used.
    pub fn prune_expired(&mut self) -> usize {
        self.prune_expired_at(Self::now_epoch_secs())
    }

    /// Deterministic variant of `prune_expired` for tests.
    pub fn prune_expired_at(&mut self, now_epoch_secs: i64) -> usize {
        let before = self.challenges.len();
        self.challenges.retain(|_, entry| {
            !Self::is_expired(entry.issued_at_epoch_secs, now_epoch_secs)
        });
        before - self.challenges.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_challenge() -> ChallengeMessage {
        ChallengeMessage::new(uuid::Uuid::new_v4(), uuid::Uuid::new_v4(), [7u8; 32])
    }

    #[test]
    fn canonical_bytes_layout_v1() {
        let challenge = sample_challenge();
        let bytes = challenge.canonical_bytes();
        assert_eq!(bytes.len(), 70);
        // CANONICAL_ENCODING_VERSION = 1, protocol_version = 1 (both BE).
        assert_eq!(&bytes[0..2], &[0, 1]);
        assert_eq!(&bytes[2..4], &[0, 1]);
        // session_id at 4..20, node_identity_id at 20..36.
        assert_eq!(&bytes[4..20], challenge.session_id.as_bytes());
        assert_eq!(&bytes[20..36], challenge.node_identity_id.as_bytes());
        assert_eq!(&bytes[36..68], &challenge.nonce);
        assert_eq!(&bytes[68..70], &[0, 1]);
    }

    #[test]
    fn canonical_bytes_are_deterministic() {
        let challenge = sample_challenge();
        assert_eq!(challenge.canonical_bytes(), challenge.canonical_bytes());
    }

    #[test]
    fn challenge_is_consumed_atomically_on_first_attempt() {
        let mut state = IdentityChallengeState::default();
        let challenge = sample_challenge();
        state.begin(challenge.clone());
        let session_id = challenge.session_id;

        assert_eq!(state.state(&session_id), Some(ChallengeState::Pending));
        assert_eq!(state.consume(&session_id), Some(challenge.clone()));
        assert_eq!(state.state(&session_id), Some(ChallengeState::Consumed));

        // Replay / retry after a failure is rejected.
        assert_eq!(state.consume(&session_id), None);
        assert_eq!(state.state(&session_id), Some(ChallengeState::Consumed));
    }

    #[test]
    fn unknown_challenge_is_rejected() {
        let mut state = IdentityChallengeState::default();
        assert_eq!(state.consume(&uuid::Uuid::new_v4()), None);
    }

    #[test]
    fn new_session_cannot_consume_another() {
        let mut state = IdentityChallengeState::default();
        let first = sample_challenge();
        let second = sample_challenge();
        state.begin(first.clone());
        state.begin(second.clone());

        assert_eq!(state.consume(&first.session_id), Some(first.clone()));
        assert_eq!(state.consume(&first.session_id), None);
        // second is independent and still consumable once.
        assert_eq!(state.consume(&second.session_id), Some(second));
    }

    // -------------------------------------------------------------------------
    // SEC-001-B / SEC-001-C: TTL, expiry, outstanding-challenge bound
    // -------------------------------------------------------------------------

    /// Fixed clock base so expiry tests are deterministic (no real sleeps).
    const FIXED_NOW: i64 = 1_000_000;
    const TTL_SECS: i64 = CHALLENGE_TTL.as_secs() as i64;

    #[test]
    fn expired_challenge_is_rejected_and_removed_on_consume() {
        let mut state = IdentityChallengeState::default();
        let challenge = sample_challenge();
        state.try_begin(challenge.clone(), FIXED_NOW);

        // Just inside the TTL: consumable.
        assert_eq!(
            state.consume_at(&challenge.session_id, FIXED_NOW + TTL_SECS - 1),
            Some(challenge.clone())
        );
        // Consumed stays one-shot.
        assert_eq!(
            state.consume_at(&challenge.session_id, FIXED_NOW + TTL_SECS - 1),
            None
        );
        assert_eq!(state.state(&challenge.session_id), Some(ChallengeState::Consumed));
    }

    #[test]
    fn expired_challenge_is_rejected_at_ttl_boundary() {
        let mut state = IdentityChallengeState::default();
        let challenge = sample_challenge();
        state.try_begin(challenge.clone(), FIXED_NOW);

        // At exactly TTL the challenge is expired (>=).
        assert_eq!(
            state.consume_at(&challenge.session_id, FIXED_NOW + TTL_SECS),
            None
        );
        // Expired entries are removed, not retained.
        assert_eq!(state.state(&challenge.session_id), None);
        assert!(state.is_empty());
    }

    #[test]
    fn expired_challenge_is_never_consumable_even_pending() {
        let mut state = IdentityChallengeState::default();
        let challenge = sample_challenge();
        state.try_begin(challenge.clone(), FIXED_NOW);

        assert_eq!(
            state.consume_at(&challenge.session_id, FIXED_NOW + TTL_SECS + 10),
            None
        );
        assert_eq!(state.state(&challenge.session_id), None);
        assert_eq!(state.len(), 0);
    }

    #[test]
    fn max_outstanding_challenges_bounds_the_store() {
        let mut state = IdentityChallengeState::default();
        let mut accepted = 0;
        for _ in 0..(MAX_OUTSTANDING_CHALLENGES + 10) {
            if state.try_begin(sample_challenge(), FIXED_NOW) {
                accepted += 1;
            }
        }
        assert_eq!(accepted, MAX_OUTSTANDING_CHALLENGES);
        assert_eq!(state.len(), MAX_OUTSTANDING_CHALLENGES);
    }

    #[test]
    fn expired_challenges_do_not_count_toward_capacity() {
        let mut state = IdentityChallengeState::default();
        // Fill the store with already-expired challenges.
        for _ in 0..MAX_OUTSTANDING_CHALLENGES {
            assert!(state.try_begin(sample_challenge(), FIXED_NOW - 2 * TTL_SECS));
        }
        assert_eq!(state.len(), MAX_OUTSTANDING_CHALLENGES);

        // A fresh begin prunes the expired entries and succeeds.
        let fresh = sample_challenge();
        assert!(state.try_begin(fresh.clone(), FIXED_NOW));
        assert_eq!(state.len(), 1);
        assert_eq!(state.state(&fresh.session_id), Some(ChallengeState::Pending));
    }

    #[test]
    fn prune_expired_removes_only_expired() {
        let mut state = IdentityChallengeState::default();
        // Insert the fresh challenge first: `try_begin` prunes expired entries
        // on insertion, so the expired one must be added after it.
        let fresh = sample_challenge();
        let old = sample_challenge();
        state.try_begin(fresh.clone(), FIXED_NOW);
        state.try_begin(old.clone(), FIXED_NOW - 2 * TTL_SECS);
        assert_eq!(state.len(), 2);

        let removed = state.prune_expired_at(FIXED_NOW);
        assert_eq!(removed, 1);
        assert_eq!(state.len(), 1);
        assert_eq!(state.state(&fresh.session_id), Some(ChallengeState::Pending));
        assert_eq!(state.state(&old.session_id), None);
    }

    #[test]
    fn consuming_challenge_removes_expired_entry_opportunistically() {
        let mut state = IdentityChallengeState::default();
        let active = sample_challenge();
        let expired = sample_challenge();
        state.try_begin(active.clone(), FIXED_NOW);
        state.try_begin(expired.clone(), FIXED_NOW - 2 * TTL_SECS);

        // Consuming the active challenge must not touch the expired one, but a
        // later prune cleans it up.
        assert_eq!(
            state.consume_at(&active.session_id, FIXED_NOW),
            Some(active.clone())
        );
        assert_eq!(state.len(), 2);
        assert_eq!(state.prune_expired_at(FIXED_NOW), 1);
        assert_eq!(state.len(), 1);
    }
}
